services:
  backend:
    build: .
    container_name: pricing-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ../fabric-samples:/usr/src/fabric-samples
    working_dir: /usr/src/app
    extra_hosts:
      - "localhost:host-gateway"
